FROM python:3.9-slim as base
WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY . /app

ENV OPENAI_API_KEY=""
ENV TELEGRAM_BOT_TOKEN=""
ENV QA_TEXT_URL=""

FROM base as app
WORKDIR /app
CMD ["python", "telegram_bot.py"]
